//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.05 at 03:46:46 PM EET 
//


package com.bitbank.smsnotification.domain.kyivstar.cpa;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for device-type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="device-type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="nokia"/>
 *     &lt;enumeration value="nokia-logo"/>
 *     &lt;enumeration value="siemens"/>
 *     &lt;enumeration value="ems"/>
 *     &lt;enumeration value="motorola"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "device-type")
@XmlEnum
public enum DeviceType {

    @XmlEnumValue("nokia")
    NOKIA("nokia"),
    @XmlEnumValue("nokia-logo")
    NOKIA_LOGO("nokia-logo"),
    @XmlEnumValue("siemens")
    SIEMENS("siemens"),
    @XmlEnumValue("ems")
    EMS("ems"),
    @XmlEnumValue("motorola")
    MOTOROLA("motorola");
    private final String value;

    DeviceType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DeviceType fromValue(String v) {
        for (DeviceType c: DeviceType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
