//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.05 at 03:46:46 PM EET 
//


package com.bitbank.smsnotification.domain.kyivstar.cpa;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bitbank.smsnotification.domain.kyivstar.cpa package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MessageBodyBodyPart_QNAME = new QName("", "body-part");
    private final static QName _MessageStatus_QNAME = new QName("", "status");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bitbank.smsnotification.domain.kyivstar.cpa
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link Report }
     * 
     */
    public Report createReport() {
        return new Report();
    }

    /**
     * Create an instance of {@link Message.Body }
     * 
     */
    public Message.Body createMessageBody() {
        return new Message.Body();
    }

    /**
     * Create an instance of {@link Message.Status }
     * 
     */
    public Message.Status createMessageStatus() {
        return new Message.Status();
    }

    /**
     * Create an instance of {@link Report.Status }
     * 
     */
    public Report.Status createReportStatus() {
        return new Report.Status();
    }

    /**
     * Create an instance of {@link Message.Body.BodyPart }
     * 
     */
    public Message.Body.BodyPart createMessageBodyBodyPart() {
        return new Message.Body.BodyPart();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Message.Body.BodyPart }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "body-part", scope = Message.Body.class)
    public JAXBElement<Message.Body.BodyPart> createMessageBodyBodyPart(Message.Body.BodyPart value) {
        return new JAXBElement<Message.Body.BodyPart>(_MessageBodyBodyPart_QNAME, Message.Body.BodyPart.class, Message.Body.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Message.Status }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "status", scope = Message.class)
    public JAXBElement<Message.Status> createMessageStatus(Message.Status value) {
        return new JAXBElement<Message.Status>(_MessageStatus_QNAME, Message.Status.class, Message.class, value);
    }

}
