package com.bitbank.siebel.phonebyhash;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-10-01T14:59:10.166+03:00
 * Generated source version: 2.7.5
 * 
 */
@WebService(targetNamespace = "http://siebel.com/CustomUI", name = "BIT_spcUtils")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface BITSpcUtils {

    @WebMethod(action = "rpc/http://siebel.com/CustomUI:getMobilePhoneByCardNum")
    public void getMobilePhoneByCardNum(
        @WebParam(partName = "hashCardNum", name = "hashCardNum")
        java.lang.String hashCardNum,
        @WebParam(partName = "errorCode", mode = WebParam.Mode.OUT, name = "errorCode")
        javax.xml.ws.Holder<java.lang.String> errorCode,
        @WebParam(partName = "errorText", mode = WebParam.Mode.OUT, name = "errorText")
        javax.xml.ws.Holder<java.lang.String> errorText,
        @WebParam(partName = "mobilePhone", mode = WebParam.Mode.OUT, name = "mobilePhone")
        javax.xml.ws.Holder<java.lang.String> mobilePhone
    );
}
