
package com.bitbank.siebel.phonebyhash;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import com.bitbank.bitutils.domain.soapheader.cxf.Security;
import com.bitbank.bitutils.utils.SoapUtils;
import org.apache.cxf.endpoint.Client;
import org.apache.cxf.frontend.ClientProxy;
import org.apache.cxf.headers.Header;
import org.apache.cxf.interceptor.LoggingInInterceptor;
import org.apache.cxf.interceptor.LoggingOutInterceptor;
import org.apache.cxf.jaxb.JAXBDataBinding;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.BindingProvider;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-10-01T14:59:10.044+03:00
 * Generated source version: 2.7.5
 * 
 */
public final class BITSpcUtils_BITSpcUtils_Client {

    private static final QName SERVICE_NAME = new QName("http://siebel.com/CustomUI", "BIT_spcUtils");

    private BITSpcUtils_BITSpcUtils_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        BITSpcUtils_Service ss = new BITSpcUtils_Service();
        BITSpcUtils port = ss.getBITSpcUtils();

        Client client = ClientProxy.getClient(port);
        client.getInInterceptors().add(new LoggingInInterceptor());
        client.getOutInterceptors().add(new LoggingOutInterceptor());

        List<Header> headers = new ArrayList<>();
        headers.add(new Header(new QName(Security.NAMESPACE_SECURITY, "Security", Security.NAMEPREFIX_SECURITY),
                                new Security("SADMIN", "SADMIN"),
                                new JAXBDataBinding(Security.class)));
        client.getRequestContext().put(Header.HEADER_LIST, headers);

        System.out.println("Invoking getMobilePhoneByCardNum...");
        java.lang.String _getMobilePhoneByCardNum_hashCardNum = "cca4fe59d768849e563734c384a5a02d";
        javax.xml.ws.Holder<java.lang.String> _getMobilePhoneByCardNum_errorCode = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<java.lang.String> _getMobilePhoneByCardNum_errorText = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<java.lang.String> _getMobilePhoneByCardNum_mobilePhone = new javax.xml.ws.Holder<java.lang.String>();
        port.getMobilePhoneByCardNum(_getMobilePhoneByCardNum_hashCardNum, _getMobilePhoneByCardNum_errorCode, _getMobilePhoneByCardNum_errorText, _getMobilePhoneByCardNum_mobilePhone);

        System.out.println("getMobilePhoneByCardNum._getMobilePhoneByCardNum_errorCode=" + _getMobilePhoneByCardNum_errorCode.value);
        System.out.println("getMobilePhoneByCardNum._getMobilePhoneByCardNum_errorText=" + _getMobilePhoneByCardNum_errorText.value);
        System.out.println("getMobilePhoneByCardNum._getMobilePhoneByCardNum_mobilePhone=" + _getMobilePhoneByCardNum_mobilePhone.value);
    }

}
