package com.bitbank.siebel.phonebyhash;

import org.apache.cxf.feature.Features;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-10-01T14:59:10.183+03:00
 * Generated source version: 2.7.5
 * 
 */
@WebServiceClient(name = "BIT_spcUtils",
                  wsdlLocation = "resources://BITUtils.wsdl",
                  targetNamespace = "http://siebel.com/CustomUI") 
public class BITSpcUtils_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://siebel.com/CustomUI", "BIT_spcUtils");
    public final static QName BITSpcUtils = new QName("http://siebel.com/CustomUI", "BIT_spcUtils");
    static {
        URL url = null;
        try {
            url = BITSpcUtils_Service.class.getClassLoader().getResource("BITUtils.wsdl");
        } catch (Exception e) {
            java.util.logging.Logger.getLogger(BITSpcUtils_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "BITSpcUtils_Service.class.getClassLoader().getResource(\"BITUtils.wsdl\")");
        }
        WSDL_LOCATION = url;
    }

    public BITSpcUtils_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BITSpcUtils_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BITSpcUtils_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BITSpcUtils_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BITSpcUtils_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BITSpcUtils_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns BITSpcUtils
     */
    @WebEndpoint(name = "BIT_spcUtils")
    public BITSpcUtils getBITSpcUtils() {
        return super.getPort(BITSpcUtils, BITSpcUtils.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BITSpcUtils
     */
    @WebEndpoint(name = "BIT_spcUtils")
    public BITSpcUtils getBITSpcUtils(WebServiceFeature... features) {
        return super.getPort(BITSpcUtils, BITSpcUtils.class, features);
    }

}
